### ISSUE TITLE
您好！方便帮我看下这种错误吗

### ISSUE THREAD

**Issue by lpf013** [SwimmingLiu/YOLOSHOW#10]
TypeError: arguments did not match any overloaded call:
  QPushButton(parent: typing.Optional[QWidget] = None): argument 'parent' has unexpected type 'PySide6.QtWidgets.QWidget'
  QPushButton(text: str, parent: typing.Optional[QWidget] = None): not enough arguments
  QPushButton(icon: QIcon, text: str, parent: typing.Optional[QWidget] = None): not enough arguments

**Comment by SwimmingLiu** [comment]
建议重装依赖
```
pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install "PySide6-Fluent-Widgets[full]" -i https://pypi.tuna.tsinghua.edu.cn/simple
pip install -U Pyside6 -i https://pypi.tuna.tsinghua.edu.cn/simple
