### ISSUE TITLE
无法摄像头检测

### ISSUE THREAD

**Issue by Escape0527** [SwimmingLiu/YOLOSHOW#11]
问题：点击摄像头图标，仅打开1s摄像头后自动关闭。UI无显示。
![屏幕截图 2024-04-09 114816](https://github.com/SwimmingLiu/YOLOSHOW/assets/63070461/4606e527-f7c3-4e01-9a1f-b6e6c2b26c08)

**Comment by SwimmingLiu** [comment]
点一下左下角播放按钮

**Comment by Escape0527** [comment]
> 点一下左下角播放按钮

会显示 Please select the Image/Video before starting detection

**Comment by SwimmingLiu** [comment]
先点击camera_0，然后点击左下角播放按钮

**Comment by Escape0527** [comment]
> 先点击camera_0，然后点击左下角播放按钮

好的，问题解决了！感谢🙏
