### ISSUE TITLE
主页面

### ISSUE THREAD

**Issue by chenhongming** [SwimmingLiu/YOLOSHOW#12]
用qtdesigner 打开 YOLOSHOWUI.ui 后，不显示settings 那一栏的控件，如下图，如何才能显示出来并编辑它，主要是能显示出来。

![捕获3](https://github.com/SwimmingLiu/YOLOSHOW/assets/29920966/b226769d-380a-49d5-8b24-540a84a2c54c)

期望您的回复和答疑，感谢。

**Comment by SwimmingLiu** [comment]
settingbox最小宽度修改为220

**Comment by chenhongming** [comment]
好的，感谢
