### ISSUE TITLE
字体相关

### ISSUE THREAD

**Issue by chenhongming** [SwimmingLiu/YOLOSHOW#15]
在qt-designer 中 ，如图选择了 微软雅黑 确定后，还是Times New Roman，还是哪些位置需要改动才能生效。

![捕获4](https://github.com/SwimmingLiu/YOLOSHOW/assets/29920966/d88d6027-ae48-4a45-ab62-ea7cc04dce81)

期待您的回复！

**Comment by SwimmingLiu** [comment]
选中src_menu组件 -> 右键修改 `stylesheet` ->  修改QSS中的Font
