### ISSUE TITLE
显示相关

### ISSUE THREAD

**Issue by chenhongming** [SwimmingLiu/YOLOSHOW#16]
Win10 下 四周没有黑边，Ubuntu20.04 下，四周有黑边，如下图所示。
是否完全是由系统引起的，或者有没有工程下的某个部分可以解决这个问题。

![捕获6](https://github.com/SwimmingLiu/YOLOSHOW/assets/29920966/89a4e54f-0879-4666-b48c-7361a5f37665)
![捕获5](https://github.com/SwimmingLiu/YOLOSHOW/assets/29920966/23b3df37-6d69-4540-b602-22dd26cdd1c7)

期待您的回复！

**Comment by SwimmingLiu** [comment]
个人觉得是系统不兼容的原因，我在Ubuntu22.04显示是没有黑边的。

**Comment by SwimmingLiu** [comment]
Tested in Ubuntu22.04 （: 或许你可以换一个OS Theme Color

![微信图片_20240422174241](https://github.com/SwimmingLiu/YOLOSHOW/assets/53814462/362418be-198d-4056-915c-2aa562d987d9)
