### ISSUE TITLE
setting显示异常

### ISSUE THREAD

**Issue by PHaohui** [SwimmingLiu/YOLOSHOW#20]
![question](https://github.com/SwimmingLiu/YOLOSHOW/assets/102863113/ba6545d8-22fb-4672-85e9-e966baea5474)
通过您的教程，我顺利打开了显示界面，功能完善。
唯一的问题就是打开setting后右边显示异常，请问怎么修改？

**Comment by SwimmingLiu** [comment]
1. 放大镜图标可能是系统不兼容
2. qtdesigner调整一下sliderbox和sliderbar的宽度就行 （因为我的电脑显示是正常的，所以我这边没法调试）
