### ISSUE TITLE
一个菜鸟问题，通过直接更改UI的py文件内的主界面文字，保存后无法生效

### ISSUE THREAD

**Issue by Escape0527** [SwimmingLiu/YOLOSHOW#23]
通过Pyside6 6.6.3的UIC转换的py文件无法生效，打开后，内部代码很多错误，证明转换失败。选择直接修改现有UI的py文件。更改title显示文字，保存后，执行main.py。没有获得更改后的效果。show和vs都修改了。提前感谢作者解答！
![屏幕截图 2024-05-13 024645](https://github.com/SwimmingLiu/YOLOSHOW/assets/63070461/5bc90489-b235-4bb5-acb6-50989ca96b89)
![屏幕截图 2024-05-13 024659](https://github.com/SwimmingLiu/YOLOSHOW/assets/63070461/10c6fda1-a5c3-4f7b-9ad5-83e34db62a90)
![屏幕截图 2024-05-13 025249](https://github.com/SwimmingLiu/YOLOSHOW/assets/63070461/b71b834a-6be2-4e7b-9e5d-6ad46433bfca)

**Comment by SwimmingLiu** [comment]
建议用qtdesigner修改，然后ui转py
