### ISSUE TITLE
改进模型导出的pt文件都无法正常运行检测和分割

### ISSUE THREAD

**Issue by Zzj-pcl** [SwimmingLiu/YOLOSHOW#24]

**Comment by SwimmingLiu** [comment]
如果是YOLOv5、v7、v9改进之后的模型，需要把改进的部分加在YOLOSHOW的models文件夹内。 如果是v8，把ultrlaytics卸载掉，然后复制改进过的ultralytics包到YOLOSHOW根目录下面就行。

**Comment by Zzj-pcl** [comment]
改进过的ultralytics包复制到yolocode文件夹运行出现版本各种问题
