### ISSUE TITLE
YOLOV10好像还是用不了，运行报错，v8可以

### ISSUE THREAD

**Issue by LeonYWang** [SwimmingLiu/YOLOSHOW#26]
AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from 'D:\\PythonProject\\GitHub\\YOLOSHOW-YOLOSHOW_v2.3.3\\Lib\\site-packages\\ultralytics\\utils\\loss.py'>

**Comment by SwimmingLiu** [comment]
`pip install -U ultralyitcs`
安装最新的ultrlaytics版本试试
