### ISSUE TITLE
运行较大模型时，载入文件夹运行时，程序可能会崩溃

### ISSUE THREAD

**Issue by vipzms** [SwimmingLiu/YOLOSHOW#28]
载入文件夹运行时，当载入较大模型，运行速度比较慢时，程序可能会崩溃，测试修改延时到500ms时，问题消失。
（推测应该是线程冲突导致，建议加线程锁等方式，代码内容较多，我这边自己不太好摸索。）
例如运行yolov8l.pt时，输入图片2048*2048图片文件夹，延时设置1ms，点击运行，两三张图后程序崩溃。

**Comment by SwimmingLiu** [comment]
OK 后续加入改进的todo list
