### ISSUE TITLE
您好，主界面右上角的图标应该如何修改，谢谢

### ISSUE THREAD

**Issue by xlnn** [SwimmingLiu/YOLOSHOW#3]
您好，主界面右上角的图标应该如何修改，
我的操作修改ui文件下的.ui文件如下所示，并进行了：pyside6-uic YOLOSHOWUI.ui > YOLOSHOWUI.py，但是图标并不显示，这是为什么呢？谢谢！：
![image](https://github.com/SwimmingLiu/YOLOSHOW/assets/57608826/3e2d59ca-1569-4e43-9c5f-cb7b12e36f85)

谢谢

**Comment by SwimmingLiu** [comment]
您好，使用 `url(:/leftbox/image/11.png)` 表示的是使用qrc文件中对应的 `/leftbox/image/11.png` 文件
根据我的推断，您应该是没有修改qrc文件和对应的 `YOLOSHOWUI_rc.py`
解决方法：
1. 在qrc文件当中添加 `/leftbox/image/11.png` （推荐使用QtDesigner，直接打开 `YOLOSHOWUI.ui` ，然后添加resources）
2. 使用 `pyside6-rcc ui/YOLOSHOWUI.qrc -o YOLOSHOWUI_rc.py`，更新 `YOLOSHOWUI_rc.py`

**Comment by xlnn** [comment]
谢谢您的提醒，我没有使用`pyside6-rcc ui/YOLOSHOWUI.qrc -o YOLOSHOWUI_rc.py`，非常感谢，谢谢！

**Comment by SwimmingLiu** [comment]
不用客气
