### ISSUE TITLE
No module named 'ultralytics.data.explorer'

### ISSUE THREAD

**Issue by Wiiiink** [SwimmingLiu/YOLOSHOW#37]
下载了3.2的版本 并且更新了最新的ultralytics 还是出现了No module named 'ultralytics.data.explorer'的报错

**Comment by SwimmingLiu** [comment]
十分抱歉，由于最近忙于论文实验，没有及时维护仓库。明天我将会发布 `YOLOSHOW v4.0`， 支持YOLOv11新模型，同时优化了代码结构和兼容最新版本的 `ultralytics`

**Comment by SwimmingLiu** [comment]
再次为未及时修复仓库的bug而感到抱歉，目前 `YOLOSHOW v4.1` 已推送至仓库，请各位更新代码并查验。
