### ISSUE TITLE
导入照片检测时报错

### ISSUE THREAD

**Issue by lishihong-1** [SwimmingLiu/YOLOSHOW#7]
导入照片检测时，self.detect报错，调试发现batch返回参数多于path, im0s, s = self.batch中需要的参数
<img width="1110" alt="202F5D5F68042A365925E76DB1AD9184" src="https://github.com/SwimmingLiu/YOLOSHOW/assets/73936514/5212e196-c3b4-43ee-8d32-61ca1b5aaf67">

**Comment by SwimmingLiu** [comment]
pip install -U ultralytics 用最新版试试？
