### ISSUE TITLE
 log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, " KeyError: 15

### ISSUE THREAD

**Issue by zouzouzouzzt** [SwimmingLiu/YOLOSHOW#8]
Traceback (most recent call last):
  File "D:\project\YOLOSHOW-master\yolocode\yolov8\YOLOv8Thread.py", line 105, in run
    self.detect()
  File "D:\project\YOLOSHOW-master\yolocode\yolov8\YOLOv8Thread.py", line 190, in detect
    label_str = self.write_results(i, self.results, (p, im, im0))  # labels   /// original :s +=
  File "D:\project\YOLOSHOW-master\yolocode\yolov8\YOLOv8Thread.py", line 374, in write_results
    log_string += result.verbose()
  File "D:\project\YOLOSHOW-master\yolocode\yolov8\engine\results.py", line 327, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
KeyError: 15
我使用了官方的OBB检测权重进行旋转目标检测，报了这个错误。

**Comment by SwimmingLiu** [comment]
目前暂不支持obb检测模式，后续会考虑补上该功能

**Comment by zouzouzouzzt** [comment]
好的感谢回答，请问一下想自己添加这个功能大概怎么添加呢

**Comment by SwimmingLiu** [comment]
1. 拉取最新的ultralytics仓库YOLOv8代码，然后找到models/yolo/obb/predict.py
2. 参考YOLOv8Thread.py 改成 YOLOv8ObbThread.py
3. YOLOSHOW对应添加YOLOv8ObbThread的内容

**Comment by BAI-721** [comment]
> 我按照你的步骤改了一下，现在已经可以实现OBB检测了，但没有统计类别数和目标数，请问一下是不是遗漏了某部分代码没有改，请问一下统计类别数和目标数的代码在哪部分啊，谢谢

同问，请问怎么显示OBB的统计类别数和目标数呀，非常感谢

**Comment by SwimmingLiu** [comment]
@llllaaa519 @BAI-721 最新的版本应该是支持 `obb` 模式的，您可以 `git pull` 拉取最新代码直接使用

**Comment by BAI-721** [comment]
> [@llllaaa519](https://github.com/llllaaa519) [@BAI-721](https://github.com/BAI-721) 最新的版本应该是支持 `obb` 模式的，您可以 `git pull` 拉取最新代码直接使用

是的，是支持OBB模式的，也能正常检测图像，但是界面上方的“classes”和“targets”不显示具体的数量；而DET和SEG都可以正常的显示检测目标的数量，只有OBB不显示

**Comment by SwimmingLiu** [comment]
@BAI-721 感谢您的提醒，我会尽快修复这个 `bug`
