### ISSUE TITLE
这是什么情况，作者

### ISSUE THREAD

**Issue by yxl23** [SwimmingLiu/YOLOSHOW#9]
![image](https://github.com/SwimmingLiu/YOLOSHOW/assets/115678682/ab9e7ce0-3221-4717-b5f0-d941541b8144)

**Comment by SwimmingLiu** [comment]
你是不是把ui文件夹删掉了？

**Comment by yxl23** [comment]
没有啊

**Comment by SwimmingLiu** [comment]
截一个完整的Pycharm图片，还有你是设置当中用的conda环境图片
